
import { Nunito } from "next/font/google";
import './globals.css'
import Navbar from "./components/navbar/Navbar";
import RegisterModal from "./components/modals/RegisterModal";
import ToasterProvider from "./providers/ToasterProvider";
import LoginModal from "./components/modals/LoginModal";
import getCurrentUser from "./actions/getCurrentUser";
import RecipeModal from "./components/modals/RecipeModal";
import SearchModal from "./components/modals/SearchModal";


export const metadata = {
  title: 'SunnahFoodies',
  description: 'Generated by create next app',
}

const font = Nunito({
  subsets: ["latin"]
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={font.className}>
        <ToasterProvider />
        <SearchModal/>
        <RecipeModal />
        <RegisterModal />
        <LoginModal />
        <Navbar currentUser={currentUser}/>
        <div className="pb-20 pt-28 " >
          {children}
        </div>
        </body>
    </html>
  )
}
